import type {
  Account,
  Category,
  CategoryInsight,
  CashflowPoint,
  MerchantInsight,
  OverviewSnapshot,
  ReviewQueueItem,
  Rule,
  Transaction,
  TransactionDetail,
  TransactionEvent,
} from "@/lib/types/finance";

export const sampleCategories: Category[] = [
  {
    id: "housing-rent",
    label: "Housing",
    group: "Essential",
    sublabel: "Rent",
    color: "#55d0ff",
  },
  {
    id: "groceries",
    label: "Groceries",
    group: "Essential",
    sublabel: "Food at home",
    color: "#8f7cff",
  },
  {
    id: "dining",
    label: "Dining",
    group: "Lifestyle",
    sublabel: "Restaurants",
    color: "#4cf2c5",
  },
  {
    id: "salary",
    label: "Salary",
    group: "Income",
    sublabel: "Payroll",
    color: "#74ff9f",
  },
  {
    id: "transfers",
    label: "Transfers",
    group: "Internal",
    sublabel: "Linked accounts",
    color: "#8992a5",
  },
  {
    id: "software",
    label: "Software",
    group: "Lifestyle",
    sublabel: "Subscriptions",
    color: "#f6b73c",
  },
  {
    id: "travel",
    label: "Travel",
    group: "Lifestyle",
    sublabel: "Trips",
    color: "#ff7c9d",
  },
];

export const sampleAccounts: Account[] = [
  {
    id: "acct-checking",
    name: "Main Checking",
    institution: "Schwab",
    type: "checking",
    subtype: "checking",
    currency: "USD",
    mask: "1842",
    currentBalance: 14890.42,
    availableBalance: 14650.42,
  },
  {
    id: "acct-savings",
    name: "Emergency Savings",
    institution: "Schwab",
    type: "savings",
    subtype: "high_yield_savings",
    currency: "USD",
    mask: "0158",
    currentBalance: 32750.1,
    availableBalance: 32750.1,
  },
  {
    id: "acct-amex",
    name: "Amex Gold",
    institution: "American Express",
    type: "credit",
    subtype: "credit_card",
    currency: "USD",
    mask: "9013",
    currentBalance: -1684.21,
    availableBalance: -1684.21,
  },
];

const sampleRawEvents: TransactionEvent[] = [
  {
    eventId: "evt-001",
    importBatchId: "batch-csv-demo",
    sourceName: "csv",
    sourceTransactionId: "csv-001",
    sourceAccountId: "acct-checking",
    eventType: "added",
    eventTimestamp: "2026-03-25T08:15:00.000Z",
    payload: {
      description: "PAYROLL ACME INC",
      amount: 6850,
    },
  },
  {
    eventId: "evt-002",
    importBatchId: "batch-csv-demo",
    sourceName: "csv",
    sourceTransactionId: "csv-002",
    sourceAccountId: "acct-checking",
    eventType: "added",
    eventTimestamp: "2026-03-24T19:10:00.000Z",
    payload: {
      description: "WHOLEFOODS 10429",
      amount: -132.42,
    },
  },
];

export const sampleTransactions: Transaction[] = [
  {
    transactionId: "txn-001",
    sourceTransactionId: "csv-001",
    canonicalGroupId: "group-payroll-2026-03",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-25T08:15:00.000Z",
    postedAt: "2026-03-25",
    pending: false,
    direction: "inflow",
    transactionClass: "income",
    signedAmount: 6850,
    merchantRaw: "ACME INC",
    merchantNorm: "acme",
    descriptionRaw: "PAYROLL ACME INC",
    descriptionNorm: "payroll acme inc",
    institutionCategory: "Payroll",
    derivedCategoryId: "salary",
    categoryLabel: "Salary",
    subcategoryId: null,
    confidenceScore: 1,
    classificationSource: "merchant_rule",
    ruleId: "rule-salary-payroll",
    isTransfer: false,
    isDuplicate: false,
    notes: ["Monthly salary deposit landed as expected."],
    keywordArray: ["payroll", "salary", "acme"],
    rawPayloadJson: {
      source: "csv",
      memo: "ACH CREDIT",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-25T08:15:00.000Z",
        source: "merchant_rule",
        confidenceScore: 1,
        categoryId: "salary",
        categoryLabel: "Salary",
        note: "Matched payroll keyword and employer alias.",
      },
    ],
  },
  {
    transactionId: "txn-002",
    sourceTransactionId: "csv-002",
    canonicalGroupId: "group-groceries-2026-03-24",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-24T18:58:00.000Z",
    postedAt: "2026-03-24",
    pending: false,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -132.42,
    merchantRaw: "WHOLEFOODS 10429",
    merchantNorm: "whole foods",
    descriptionRaw: "WHOLEFOODS 10429 LOS ANGELES CA",
    descriptionNorm: "whole foods los angeles ca",
    institutionCategory: "Groceries",
    derivedCategoryId: "groceries",
    categoryLabel: "Groceries",
    subcategoryId: null,
    confidenceScore: 0.95,
    classificationSource: "merchant_rule",
    ruleId: "rule-whole-foods",
    isTransfer: false,
    isDuplicate: false,
    notes: ["Weekly grocery run."],
    keywordArray: ["whole", "foods", "grocery"],
    rawPayloadJson: {
      source: "csv",
      location: "Los Angeles",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-24T19:10:00.000Z",
        source: "merchant_rule",
        confidenceScore: 0.95,
        categoryId: "groceries",
        categoryLabel: "Groceries",
        note: "Exact merchant alias match.",
      },
    ],
  },
  {
    transactionId: "txn-003",
    sourceTransactionId: "csv-003",
    canonicalGroupId: "group-rent-2026-03",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-01T16:00:00.000Z",
    postedAt: "2026-03-01",
    pending: false,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -2850,
    merchantRaw: "VISTA PROPERTY MGMT",
    merchantNorm: "vista property mgmt",
    descriptionRaw: "ACH DEBIT VISTA PROPERTY MGMT",
    descriptionNorm: "ach debit vista property mgmt",
    institutionCategory: "Rent",
    derivedCategoryId: "housing-rent",
    categoryLabel: "Housing",
    subcategoryId: null,
    confidenceScore: 1,
    classificationSource: "manual_override",
    ruleId: "override-rent",
    isTransfer: false,
    isDuplicate: false,
    notes: ["Manual override locked this to rent."],
    keywordArray: ["rent", "ach", "property"],
    rawPayloadJson: {
      source: "csv",
      channel: "ach",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-01T16:00:00.000Z",
        source: "manual_override",
        confidenceScore: 1,
        categoryId: "housing-rent",
        categoryLabel: "Housing",
        note: "Confirmed by user after first import.",
      },
    ],
  },
  {
    transactionId: "txn-004",
    sourceTransactionId: "csv-004",
    canonicalGroupId: "group-transfer-2026-03-18",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-18T14:00:00.000Z",
    postedAt: "2026-03-18",
    pending: false,
    direction: "outflow",
    transactionClass: "transfer",
    signedAmount: -1000,
    merchantRaw: "SCHWAB TRANSFER",
    merchantNorm: "schwab transfer",
    descriptionRaw: "ONLINE TRANSFER TO SAVINGS",
    descriptionNorm: "online transfer to savings",
    institutionCategory: "Transfer",
    derivedCategoryId: "transfers",
    categoryLabel: "Transfers",
    subcategoryId: null,
    confidenceScore: 0.98,
    classificationSource: "history",
    ruleId: "rule-schwab-transfer",
    isTransfer: true,
    isDuplicate: false,
    notes: ["Matched to linked savings account."],
    keywordArray: ["transfer", "savings", "linked"],
    rawPayloadJson: {
      source: "csv",
      linkedAccountId: "acct-savings",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-18T14:00:00.000Z",
        source: "history",
        confidenceScore: 0.98,
        categoryId: "transfers",
        categoryLabel: "Transfers",
        note: "Matched historical linked-account transfer pattern.",
      },
    ],
  },
  {
    transactionId: "txn-005",
    sourceTransactionId: "csv-005",
    canonicalGroupId: "group-transfer-2026-03-18",
    accountId: "acct-savings",
    accountName: "Emergency Savings",
    accountType: "savings",
    authorizedAt: "2026-03-18T14:04:00.000Z",
    postedAt: "2026-03-18",
    pending: false,
    direction: "inflow",
    transactionClass: "transfer",
    signedAmount: 1000,
    merchantRaw: "SCHWAB TRANSFER",
    merchantNorm: "schwab transfer",
    descriptionRaw: "ONLINE TRANSFER FROM CHECKING",
    descriptionNorm: "online transfer from checking",
    institutionCategory: "Transfer",
    derivedCategoryId: "transfers",
    categoryLabel: "Transfers",
    subcategoryId: null,
    confidenceScore: 0.98,
    classificationSource: "history",
    ruleId: "rule-schwab-transfer",
    isTransfer: true,
    isDuplicate: false,
    notes: ["Mirror leg of the internal transfer."],
    keywordArray: ["transfer", "checking", "linked"],
    rawPayloadJson: {
      source: "csv",
      linkedAccountId: "acct-checking",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-18T14:04:00.000Z",
        source: "history",
        confidenceScore: 0.98,
        categoryId: "transfers",
        categoryLabel: "Transfers",
        note: "Paired with checking leg using amount and date window.",
      },
    ],
  },
  {
    transactionId: "txn-006",
    sourceTransactionId: "csv-006",
    canonicalGroupId: "group-dining-2026-03-22",
    accountId: "acct-amex",
    accountName: "Amex Gold",
    accountType: "credit",
    authorizedAt: "2026-03-22T20:11:00.000Z",
    postedAt: "2026-03-23",
    pending: false,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -89.6,
    merchantRaw: "SUSHI GEN",
    merchantNorm: "sushi gen",
    descriptionRaw: "SUSHI GEN DTLA",
    descriptionNorm: "sushi gen dtla",
    institutionCategory: "Dining",
    derivedCategoryId: "dining",
    categoryLabel: "Dining",
    subcategoryId: null,
    confidenceScore: 0.85,
    classificationSource: "history",
    ruleId: "rule-sushi-gen",
    isTransfer: false,
    isDuplicate: false,
    notes: ["Dinner with friends."],
    keywordArray: ["sushi", "restaurant"],
    rawPayloadJson: {
      source: "csv",
      cardPresent: true,
    },
    classificationHistory: [
      {
        timestamp: "2026-03-23T00:00:00.000Z",
        source: "history",
        confidenceScore: 0.85,
        categoryId: "dining",
        categoryLabel: "Dining",
        note: "Merchant seen three times on credit account.",
      },
    ],
  },
  {
    transactionId: "txn-007",
    sourceTransactionId: "csv-007",
    canonicalGroupId: "group-software-2026-03-20",
    accountId: "acct-amex",
    accountName: "Amex Gold",
    accountType: "credit",
    authorizedAt: "2026-03-20T11:32:00.000Z",
    postedAt: "2026-03-20",
    pending: false,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -32,
    merchantRaw: "NOTION LABS",
    merchantNorm: "notion labs",
    descriptionRaw: "NOTION LABS SUBSCRIPTION",
    descriptionNorm: "notion labs subscription",
    institutionCategory: "Software",
    derivedCategoryId: "software",
    categoryLabel: "Software",
    subcategoryId: null,
    confidenceScore: 0.95,
    classificationSource: "merchant_rule",
    ruleId: "rule-notion",
    isTransfer: false,
    isDuplicate: false,
    notes: ["Recurring workspace subscription."],
    keywordArray: ["notion", "software", "subscription"],
    rawPayloadJson: {
      source: "csv",
      recurrence: "monthly",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-20T11:32:00.000Z",
        source: "merchant_rule",
        confidenceScore: 0.95,
        categoryId: "software",
        categoryLabel: "Software",
        note: "Exact recurring merchant rule.",
      },
    ],
  },
  {
    transactionId: "txn-008",
    sourceTransactionId: "csv-008",
    canonicalGroupId: "group-travel-2026-03-12",
    accountId: "acct-amex",
    accountName: "Amex Gold",
    accountType: "credit",
    authorizedAt: "2026-03-12T07:20:00.000Z",
    postedAt: "2026-03-12",
    pending: false,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -248.56,
    merchantRaw: "UBER TRIP",
    merchantNorm: "uber",
    descriptionRaw: "UBER TRIP SAN FRANCISCO",
    descriptionNorm: "uber trip san francisco",
    institutionCategory: "Travel",
    derivedCategoryId: "travel",
    categoryLabel: "Travel",
    subcategoryId: null,
    confidenceScore: 0.7,
    classificationSource: "institution_category",
    ruleId: null,
    isTransfer: false,
    isDuplicate: false,
    notes: ["Airport transfer and city rides during conference."],
    keywordArray: ["uber", "travel", "trip"],
    rawPayloadJson: {
      source: "csv",
      city: "San Francisco",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-12T07:20:00.000Z",
        source: "institution_category",
        confidenceScore: 0.7,
        categoryId: "travel",
        categoryLabel: "Travel",
        note: "Fallback to provider travel category.",
      },
    ],
  },
  {
    transactionId: "txn-009",
    sourceTransactionId: "csv-009",
    canonicalGroupId: "group-fee-2026-03-09",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-09T09:30:00.000Z",
    postedAt: "2026-03-09",
    pending: false,
    direction: "outflow",
    transactionClass: "fee",
    signedAmount: -12,
    merchantRaw: "ATM FEE",
    merchantNorm: "atm fee",
    descriptionRaw: "ATM FEE NON-NETWORK",
    descriptionNorm: "atm fee non network",
    institutionCategory: "Fees",
    derivedCategoryId: "transfers",
    categoryLabel: "Transfers",
    subcategoryId: null,
    confidenceScore: 0.55,
    classificationSource: "fallback",
    ruleId: null,
    isTransfer: false,
    isDuplicate: false,
    notes: ["Should probably become its own fee category later."],
    keywordArray: ["atm", "fee"],
    rawPayloadJson: {
      source: "csv",
      atmNetwork: "non-network",
    },
    classificationHistory: [
      {
        timestamp: "2026-03-09T09:30:00.000Z",
        source: "fallback",
        confidenceScore: 0.55,
        categoryId: "transfers",
        categoryLabel: "Transfers",
        note: "Low-confidence fallback awaiting category cleanup.",
      },
    ],
  },
  {
    transactionId: "txn-010",
    sourceTransactionId: "csv-010",
    canonicalGroupId: "group-review-2026-03-26",
    accountId: "acct-checking",
    accountName: "Main Checking",
    accountType: "checking",
    authorizedAt: "2026-03-26T12:10:00.000Z",
    postedAt: "2026-03-26",
    pending: true,
    direction: "outflow",
    transactionClass: "expense",
    signedAmount: -56.31,
    merchantRaw: "SQ *LOCAL MARKET",
    merchantNorm: "local market",
    descriptionRaw: "SQ *LOCAL MARKET 4820",
    descriptionNorm: "local market",
    institutionCategory: null,
    derivedCategoryId: "groceries",
    categoryLabel: "Groceries",
    subcategoryId: null,
    confidenceScore: 0.55,
    classificationSource: "ai_suggestion",
    ruleId: null,
    isTransfer: false,
    isDuplicate: false,
    notes: ["Needs review because the merchant is new and still pending."],
    keywordArray: ["local", "market", "sq"],
    rawPayloadJson: {
      source: "csv",
      pending: true,
    },
    classificationHistory: [
      {
        timestamp: "2026-03-26T12:10:00.000Z",
        source: "ai_suggestion",
        confidenceScore: 0.55,
        categoryId: "groceries",
        categoryLabel: "Groceries",
        note: "Suggested from normalized description only.",
      },
    ],
  },
];

export const sampleTransactionDetails: Record<string, TransactionDetail> =
  Object.fromEntries(
    sampleTransactions.map((transaction) => [
      transaction.transactionId,
      {
        ...transaction,
        relatedTransfers:
          transaction.canonicalGroupId === "group-transfer-2026-03-18"
            ? sampleTransactions
                .filter(
                  (candidate) =>
                    candidate.canonicalGroupId === transaction.canonicalGroupId &&
                    candidate.transactionId !== transaction.transactionId,
                )
                .map((candidate) => ({
                  transactionId: candidate.transactionId,
                  accountName: candidate.accountName,
                  signedAmount: candidate.signedAmount,
                  postedAt: candidate.postedAt,
                }))
            : [],
        rawEvents: sampleRawEvents.filter(
          (event) => event.sourceTransactionId === transaction.sourceTransactionId,
        ),
      },
    ]),
  );

export const sampleRules: Rule[] = [
  {
    id: "rule-salary-payroll",
    name: "Payroll Deposit",
    description: "Map payroll descriptions from ACME into Salary.",
    priority: 100,
    enabled: true,
    categoryId: "salary",
    categoryLabel: "Salary",
    matchStrategy: "description_regex",
    matchValue: "payroll|direct deposit",
    confidenceBoost: 1,
    hitRate: 1,
    lastMatchedAt: "2026-03-25",
  },
  {
    id: "rule-whole-foods",
    name: "Whole Foods Groceries",
    description: "Treat Whole Foods charges as groceries by default.",
    priority: 95,
    enabled: true,
    categoryId: "groceries",
    categoryLabel: "Groceries",
    matchStrategy: "merchant_exact",
    matchValue: "whole foods",
    confidenceBoost: 0.95,
    hitRate: 0.98,
    lastMatchedAt: "2026-03-24",
  },
  {
    id: "rule-schwab-transfer",
    name: "Internal Schwab Transfers",
    description: "Pair checking and savings movements as transfers.",
    priority: 90,
    enabled: true,
    categoryId: "transfers",
    categoryLabel: "Transfers",
    matchStrategy: "merchant_contains",
    matchValue: "schwab transfer",
    confidenceBoost: 0.98,
    hitRate: 0.94,
    lastMatchedAt: "2026-03-18",
  },
  {
    id: "rule-notion",
    name: "Notion Subscription",
    description: "Bucket recurring Notion charges under software.",
    priority: 85,
    enabled: true,
    categoryId: "software",
    categoryLabel: "Software",
    matchStrategy: "merchant_exact",
    matchValue: "notion labs",
    confidenceBoost: 0.95,
    hitRate: 1,
    lastMatchedAt: "2026-03-20",
  },
];

export const sampleReviewQueue: ReviewQueueItem[] = [
  {
    transactionId: "txn-010",
    merchant: "SQ *LOCAL MARKET",
    description: "SQ *LOCAL MARKET 4820",
    amount: 56.31,
    postedAt: "2026-03-26",
    suggestedCategory: "Groceries",
    confidenceScore: 0.55,
    reason: "Pending merchant with AI-only classification.",
  },
  {
    transactionId: "txn-009",
    merchant: "ATM FEE",
    description: "ATM FEE NON-NETWORK",
    amount: 12,
    postedAt: "2026-03-09",
    suggestedCategory: "Transfers",
    confidenceScore: 0.55,
    reason: "Low-confidence fallback category, no explicit fee rule yet.",
  },
];

export const sampleCashflow: CashflowPoint[] = [
  { date: "2026-03-01", inflow: 0, outflow: 2850, net: -2850 },
  { date: "2026-03-09", inflow: 0, outflow: 12, net: -12 },
  { date: "2026-03-12", inflow: 0, outflow: 248.56, net: -248.56 },
  { date: "2026-03-18", inflow: 1000, outflow: 1000, net: 0 },
  { date: "2026-03-20", inflow: 0, outflow: 32, net: -32 },
  { date: "2026-03-23", inflow: 0, outflow: 89.6, net: -89.6 },
  { date: "2026-03-24", inflow: 0, outflow: 132.42, net: -132.42 },
  { date: "2026-03-25", inflow: 6850, outflow: 0, net: 6850 },
  { date: "2026-03-26", inflow: 0, outflow: 56.31, net: -56.31 },
];

export const sampleCategoryInsights: CategoryInsight[] = [
  {
    categoryId: "housing-rent",
    label: "Housing",
    amount: 2850,
    share: 0.67,
    transactionCount: 1,
    trend: 0,
  },
  {
    categoryId: "groceries",
    label: "Groceries",
    amount: 188.73,
    share: 0.04,
    transactionCount: 2,
    trend: 0.18,
  },
  {
    categoryId: "dining",
    label: "Dining",
    amount: 89.6,
    share: 0.02,
    transactionCount: 1,
    trend: 0.11,
  },
  {
    categoryId: "software",
    label: "Software",
    amount: 32,
    share: 0.01,
    transactionCount: 1,
    trend: 0,
  },
  {
    categoryId: "travel",
    label: "Travel",
    amount: 248.56,
    share: 0.06,
    transactionCount: 1,
    trend: 0.44,
  },
];

export const sampleMerchantInsights: MerchantInsight[] = [
  {
    merchant: "VISTA PROPERTY MGMT",
    spend: 2850,
    transactions: 1,
    trend: 0,
    likelyRecurring: true,
  },
  {
    merchant: "WHOLEFOODS 10429",
    spend: 132.42,
    transactions: 1,
    trend: 0.06,
    likelyRecurring: false,
  },
  {
    merchant: "UBER TRIP",
    spend: 248.56,
    transactions: 1,
    trend: 0.44,
    likelyRecurring: false,
  },
  {
    merchant: "NOTION LABS",
    spend: 32,
    transactions: 1,
    trend: 0,
    likelyRecurring: true,
  },
];

export const sampleOverview: OverviewSnapshot = {
  totalBalance: sampleAccounts.reduce(
    (total, account) => total + account.currentBalance,
    0,
  ),
  availableCash: sampleAccounts
    .filter((account) => account.type !== "credit")
    .reduce((total, account) => total + account.availableBalance, 0),
  monthToDateSpend: Math.abs(
    sampleTransactions
      .filter((transaction) => transaction.direction === "outflow")
      .reduce((total, transaction) => total + transaction.signedAmount, 0),
  ),
  monthToDateIncome: sampleTransactions
    .filter((transaction) => transaction.direction === "inflow")
    .reduce((total, transaction) => total + transaction.signedAmount, 0),
  savingsRate: 0.41,
  largestExpense: {
    merchant: "VISTA PROPERTY MGMT",
    amount: 2850,
    postedAt: "2026-03-01",
  },
  accounts: sampleAccounts,
  cashflow: sampleCashflow,
  categoryMix: sampleCategoryInsights.map((item) => ({
    categoryId: item.categoryId,
    label: item.label,
    amount: item.amount,
    share: item.share,
  })),
  topMerchants: sampleMerchantInsights.map((item) => ({
    merchant: item.merchant,
    amount: item.spend,
    transactions: item.transactions,
    changeVsPrior: item.trend,
  })),
  reviewQueueCount: sampleReviewQueue.length,
};
